import Head from "next/head";

const HeadComponent = ({ title, meta, link, hasMaterialTable = false }) => {
  meta = meta ? [...HeadComponent.defaultProps.meta, ...meta] : HeadComponent.defaultProps.meta;
  link = link ? [...HeadComponent.defaultProps.link, ...link] : HeadComponent.defaultProps.link;

  return (
    <Head>
      <title>{title}</title>
      {meta.map((item, index) => (
        <meta name={item.name} content={item.content} key={index} />
      ))}
      {link.map((item, index) => (
        <link
          rel={item.rel}
          href={item.href}
          as={item.as && item.as}
          type={item.type && item.type}
          crossOrigin={link.crossOrigin && link.crossOrigin}
          key={index}
        />
      ))}
    </Head>
  );
};

HeadComponent.defaultProps = {
  title: "Home",
  meta: [
    {
      name: "description",
      content: "Generated by create next app",
    },
  ],
  link: [
    {
      rel: "icon",
      href: "/images/favicon.ico",
    },
  ],
};

export default HeadComponent;
